---
# Site Settings
title                    : "Pengyu Xue"
description              : "Penguin's Page (•ө•)"
repository               : "Pengyu03/Pengyu03.github.io"
google_scholar_stats_use_cdn : true

# google analytics
google_analytics_id      :  # 可在 https://analytics.google.com 获取你的 ID

# SEO Related
google_site_verification :  # 可在 https://search.google.com/search-console/about 获取验证代码
bing_site_verification   :  
baidu_site_verification  :  

# Site Author
author:
  name             : "Pengyu Xue"
  avatar           : "images/android-chrome-192x192.png"
  bio              : "Shandong University | AI4SE Enthusiast"
  location         : "Qingdao, China"
  email            : "xuepengyu@mail.sdu.edu.cn"
  googlescholar    : "https://scholar.google.com/citations?user=RiFZe1YAAAAJ&hl=en"
  github           : "Pengyu03"
  orcid            : "https://orcid.org/0009-0007-3395-9575"
  researchgate     :  
  stackoverflow    :  
  twitter          :  
  linkedin         :  

# Reading Files
include:
  - .htaccess
  - _pages
  - files
  - images
exclude:
  - docs
  - google_scholar_crawler
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - .github
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      author_profile: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:title/
timezone: Asia/Shanghai

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
